apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-react
        image: aksdevregistrycam.azurecr.io/react.frontend-i:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway-container
        image: aksdevregistrycam.azurecr.io/apigateway:latest
        ports:
        - containerPort: 8001
      imagePullSecrets:
      - name: regcred

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi-container
        image: aksdevregistrycam.azurecr.io/catalogapi:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
      
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: front-end


apiVersion: v1
kind: Service
metadata:
  name: catalogapi
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: catalogapi