apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-react
        image: aksdevregistrycam.azurecr.io/react.frontend-i  # Use any desired container image
        ports:
        - containerPort: 5000  # Port the container will listen on
