apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end-react
        image: aksdevregistrycam.azurecr.io/react.frontend-i:latest  # Use any desired container image
        ports:
        - containerPort: 5000  # Port the container will listen on
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  selector:
    app: front-end
  ports:
  - name: http
    port: 5000
    targetPort: http
    protocol: TCP
  type: LoadBalancer


