# any change happen on main branch will trigger the pipeline.
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t aksdevregistrycam.azurecr.io/react.frontend-i:tag react-frontend
      az acr login -n aksdevregistrycam
      docker push aksdevregistrycam.azurecr.io/react.frontend-i:tag

- script: cat .azdo/deploy-ci/app-deploy.yaml
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    azureResourceGroup: 'AKS-DEV'
    kubernetesCluster: 'AKS-DEV'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '.azdo/deploy-ci'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    azureContainerRegistry: 'aksdevregistrycam.azurecr.io'
    forceUpdate: false