# any change happen on main branch will trigger the pipeline.
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerCompose@0
  displayName: 'Build Docker Images'
  inputs:
    azureSubscriptionEndpoint: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    azureContainerRegistry: 'aksdevregistrycam.azurecr.io'
    dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
    action: 'Build services'
    additionalImageTags: 'latest'

- task: AzureCLI@2
  displayName: 'Push Docker Images to ACR'
  inputs:
    azureSubscription: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Log in to Azure
      az login

      # Set the Azure Container Registry name
      ACR_NAME=aksdevregistrycam

      # Define services to push
      SERVICES=("app" "apigateway" "catalog.api" "registration.service" "login.service")

      # Log in to Azure Container Registry
      az acr login --name $ACR_NAME

      for SERVICE in "${SERVICES[@]}"; do
        # Tag the Docker image with the ACR URL
        IMAGE_NAME=$ACR_NAME.azurecr.io/$SERVICE
        docker tag $SERVICE:latest $IMAGE_NAME

        # Push the Docker image to Azure Container Registry
        docker push $IMAGE_NAME
      done

- script: cat .azdo/deploy-ci/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    azureResourceGroup: 'AKS-DEV'
    kubernetesCluster: 'AKS-DEV'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '.azdo/deploy-ci'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1 (67336b9e-4aa9-4fe1-939b-d5d2efde661f)'
    azureContainerRegistry: 'aksdevregistrycam.azurecr.io'
    forceUpdate: false
