apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: ingress-nginx
spec:
  secretName: selfsigned-cert-tls
  isCA: true
  commonName: "52.226.2.60"
  issuerRef:
    name: selfsigned-issuer
