version: '3.4'

networks:
  myNetwork:
    driver: bridge

services:
  app:
    container_name: react.frontend-c
    image: react.frontend-i  
    build:
      context: react-frontend
    ports:
        - 8080:80
    networks:
      - myNetwork

  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ApiGateway
    ports:
        - 8001:80
    networks:
      - myNetwork

  catalog.api:
    container_name: mostpopularmovies
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    networks:
      - myNetwork

  registration.service:
    container_name: userregistration
    image: ${DOCKER_REGISTRY-}registrationservice
    build:
      context: RegistrationService
    networks:
      - myNetwork

  login.service:
    container_name: loginservice
    image: ${DOCKER_REGISTRY-}loginservice
    build:
      context: Login.Service
    networks:
      - myNetwork

