version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  frontend.react:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

