version: '3.4'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "443"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "443"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "443"

  registration.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "443"

  login.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "443"

