version: '3.4'

networks:
  myNetwork:
    driver: bridge

services:
  apigateway:
    container_name: apigateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway\Dockerfile
    ports:
        - 8001:80
    networks:
      - myNetwork

  catalog.api:
    container_name: mostpopularmovies
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    networks:
      - myNetwork

  app:
    container_name: react.frontend-c
    image: react.frontend-i  
    build:
      context: C:\Users\Camer\source\repos\Movies\react-frontend
    ports:
      - "8080:80" 





