version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  registration.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  login.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

