apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deployment-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - testcam.co.uk
      secretName: certificate
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 80
          - path: /api/popular
            pathType: Prefix
            backend:
              service:
                name: apigateway
                port:
                  number: 80                  





