apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend-i
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: react-frontend-i
        image: aksdevregistrycam.azurecr.io/react-frontend-i:tag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: react-frontend-i