version: '3'

services:
  super-linter:
    image: github/super-linter:latest
    container_name: super-linter
    environment:
      - RUN_LOCAL=true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: docker://github/super-linter:latest
        with:
          args: |
            --validate-attempt 1
            --validate-config-file
